apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: {{ .Values.runtimeConfig.name }}
spec:
  serviceConfig:
    name: {{ .Values.runtimeConfig.service.name }}
    namespace: {{ .Values.runtimeConfig.service.namespace }}
    port: 9443
  deploymentTemplate:
    spec:
      selector:
        matchLabels:
          pkg.crossplane.io/function: function-skyhook
      template:
        metadata:
          labels:
            pkg.crossplane.io/function: function-skyhook
        spec:
          containers:
            - name: package-runtime
              resources:
                limits:
                  cpu: 250m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
