enableTelemetry: false

nodeLinker: node-modules

## To Dev using verdaccio local registry
# npmRegistryServer: "http://localhost:4873"
# unsafeHttpWhitelist: ["localhost"]

plugins:
  - checksum: 261acd6dc39c0b6178a049fea5f33b6ce6eed61ad87d1227efcd97689d182074a222a5401d6c302cc19387097ffdd8a5787dca6680093f1f30a6209f62d6cb2f
    path: .yarn/plugins/@yarnpkg/plugin-fetch.cjs
    spec: "https://codeberg.org/devthefuture/yarn-plugin-fetch/raw/branch/master/bundles/@yarnpkg/plugin-fetch.js"

yarnPath: .yarn/releases/yarn-4.8.1.cjs
