apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: {{ .Values.function.name }}
  labels:
    {{- include "xfuncjs.labels" . | nindent 4 }}
spec:
  package: {{ .Values.function.package.repository }}/{{ .Values.function.package.name }}:{{ default .Chart.AppVersion .Values.function.package.tag }}
  packagePullPolicy: {{ .Values.function.pullPolicy }}
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: {{ .Values.runtimeConfig.name }}

