apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: {{ .Values.function.name }}
  labels:
    {{- include "xfuncjs.labels" . | nindent 4 }}
spec:
  package: {{ .Values.function.package.repository }}/{{ .Values.function.package.name }}:{{ if .Values.function.package.tag }}{{ .Values.function.package.tag | toString }}{{ else }}v{{ .Chart.AppVersion }}{{ end }}
  packagePullPolicy: {{ .Values.function.pullPolicy }}
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: {{ .Values.runtimeConfig.name }}
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false

