# Function configuration
function:
  name: function-xfuncjs
  package:
    repository: ghcr.io/socialgouv
    name: crossplane-function-js
    tag: 
  pullPolicy: IfNotPresent

# RuntimeConfig configuration
runtimeConfig:
  name: xfuncjs-runtime-config
  service:
    name: xfuncjs-server
    namespace: crossplane-system
    port: 9443

# Server configuration
config:
  # Logging configuration
  logLevel: "debug"  # debug, info, warn, error
  logFormat: "auto" # auto, text, json

  # Server configuration
  # tempDir: "/tmp/xfuncjs-server"
  # gcInterval: "5m"
  # idleTimeout: "30m"

  # Node.js configuration
  # healthCheckWait: "30s"
  # healthCheckInterval: "500ms"
  # nodeRequestTimeout: "30s"

  # TLS configuration
  # enabled by default by TLS_SERVER_CERTS_DIR env var injected by crossplane on pod's funcrtion
  tls:
    enabled: false
    # certFile: "/certs/tls.crt"
    # keyFile: "/certs/tls.key"
