// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/skyhook/service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SkyhookService_RunFunction_FullMethodName = "/skyhook.SkyhookService/RunFunction"
)

// SkyhookServiceClient is the client API for SkyhookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkyhookServiceClient interface {
	// RunFunction executes a JavaScript/TypeScript function with the provided input
	RunFunction(ctx context.Context, in *RunFunctionRequest, opts ...grpc.CallOption) (*RunFunctionResponse, error)
}

type skyhookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkyhookServiceClient(cc grpc.ClientConnInterface) SkyhookServiceClient {
	return &skyhookServiceClient{cc}
}

func (c *skyhookServiceClient) RunFunction(ctx context.Context, in *RunFunctionRequest, opts ...grpc.CallOption) (*RunFunctionResponse, error) {
	out := new(RunFunctionResponse)
	err := c.cc.Invoke(ctx, SkyhookService_RunFunction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkyhookServiceServer is the server API for SkyhookService service.
// All implementations must embed UnimplementedSkyhookServiceServer
// for forward compatibility
type SkyhookServiceServer interface {
	// RunFunction executes a JavaScript/TypeScript function with the provided input
	RunFunction(context.Context, *RunFunctionRequest) (*RunFunctionResponse, error)
	mustEmbedUnimplementedSkyhookServiceServer()
}

// UnimplementedSkyhookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkyhookServiceServer struct {
}

func (UnimplementedSkyhookServiceServer) RunFunction(context.Context, *RunFunctionRequest) (*RunFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunFunction not implemented")
}
func (UnimplementedSkyhookServiceServer) mustEmbedUnimplementedSkyhookServiceServer() {}

// UnsafeSkyhookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkyhookServiceServer will
// result in compilation errors.
type UnsafeSkyhookServiceServer interface {
	mustEmbedUnimplementedSkyhookServiceServer()
}

func RegisterSkyhookServiceServer(s grpc.ServiceRegistrar, srv SkyhookServiceServer) {
	s.RegisterService(&SkyhookService_ServiceDesc, srv)
}

func _SkyhookService_RunFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkyhookServiceServer).RunFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkyhookService_RunFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkyhookServiceServer).RunFunction(ctx, req.(*RunFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkyhookService_ServiceDesc is the grpc.ServiceDesc for SkyhookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkyhookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skyhook.SkyhookService",
	HandlerType: (*SkyhookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunFunction",
			Handler:    _SkyhookService_RunFunction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/skyhook/service.proto",
}
