name: ✔️ Tests E2E
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref_name }}

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.17.2

    - name: Install Kind
      uses: devthefuture-org/kind-with-registry-action@main
      with:
        kind_version:    v0.27.0
        kubectl_version: v1.32.2
        ingress_enabled: false
        registry_image:  registry:2
        node_image:      kindest/node:v1.32.2

    - name: Run E2E tests
      shell: bash
      # env:
      run: |
        set -eo errexit
        export KUBECONFIG="${HOME}/.kube/config"
        ./tests/install-crossplane.sh
        ./tests/e2e.sh
